// Unified media provenance: SynthID + C2PA run in parallel over one buffer and are
// folded into a single VerificationResult. Only the hash and the analysis leave this
// module — the media bytes are dropped once scanned.
import { createHash } from "node:crypto";
import { newId } from "../ids";
import type { MediaAsset, MediaKind, ProvenanceVerdict, SynthIdAnalysis, VerificationResult } from "../incident/types";
import { parseC2pa } from "./c2pa";
import { detectSynthId, type SynthIdConfig } from "./synthid";

if (typeof window !== "undefined") throw new Error("lib/provenance is server-only");

export const MAX_MEDIA_BYTES = 25 * 1024 * 1024;

export function mediaKindOf(mimeType: string): MediaKind | null {
  if (mimeType.startsWith("image/")) return "image";
  if (mimeType.startsWith("video/")) return "video";
  if (mimeType.startsWith("audio/")) return "audio";
  return null;
}

export function sha256(buffer: Buffer): string {
  return createHash("sha256").update(buffer).digest("hex");
}

/** Combine both detectors. SynthID is authoritative for Google models; C2PA covers other vendors. */
export function verdictOf(synthId: SynthIdAnalysis, c2pa: { present: boolean; aiGenerated?: boolean }): { verdict: ProvenanceVerdict; summary: string } {
  if (synthId.isGoogleAiGenerated && synthId.synthIdConfidence >= 0.8) {
    return { verdict: "ai_generated", summary: `SynthID watermark detected (${Math.round(synthId.synthIdConfidence * 100)}% confidence): generated by a Google AI model.` };
  }
  if (c2pa.present && c2pa.aiGenerated) {
    return { verdict: "ai_generated", summary: "Content Credentials declare this media was produced by a generative AI tool." };
  }
  if (synthId.isGoogleAiGenerated || (c2pa.present && c2pa.aiGenerated === undefined)) {
    return { verdict: "likely_ai", summary: "Partial provenance signal: a watermark or manifest was found but could not be fully confirmed." };
  }
  if (synthId.source === "stub" && !c2pa.present) {
    return { verdict: "inconclusive", summary: "No Content Credentials found and the SynthID detector was not available." };
  }
  return { verdict: "no_signal", summary: c2pa.present ? "Content Credentials present and do not indicate AI generation." : "No AI watermark or Content Credentials detected." };
}

export interface ScanInput {
  buffer: Buffer;
  mimeType: string;
  caseId: string;
  sourceUrl?: string;
  storageRef?: string;
}

export interface ScanOutput {
  asset: MediaAsset;
  verification: VerificationResult;
}

export async function scanMedia(input: ScanInput, synthIdConfig?: SynthIdConfig | null): Promise<ScanOutput> {
  const kind = mediaKindOf(input.mimeType);
  if (!kind) throw new Error(`Unsupported media type: ${input.mimeType}`);
  if (input.buffer.byteLength > MAX_MEDIA_BYTES) throw new Error("Media exceeds 25 MB limit");

  const at = new Date().toISOString();
  const asset: MediaAsset = {
    id: newId("ast"),
    caseId: input.caseId,
    kind,
    mimeType: input.mimeType,
    sha256: sha256(input.buffer),
    bytes: input.buffer.byteLength,
    storageRef: input.storageRef,
    sourceUrl: input.sourceUrl,
    createdAt: at,
  };

  const [synthId, c2pa] = await Promise.all([detectSynthId(input.buffer, input.mimeType, kind, synthIdConfig), parseC2pa(input.buffer, input.mimeType)]);
  const { verdict, summary } = verdictOf(synthId, c2pa);

  return {
    asset,
    verification: { id: newId("ver"), caseId: input.caseId, assetId: asset.id, synthId, c2pa, verdict, summary, createdAt: at },
  };
}

/** Fetch a scraped media URL and scan it. Returns null when the URL isn't media we can check. */
export async function scanUrl(url: string, caseId: string, synthIdConfig?: SynthIdConfig | null): Promise<ScanOutput | null> {
  const res = await fetch(url, { headers: { "User-Agent": "Reclaim-Provenance/1.0" }, signal: AbortSignal.timeout(15_000) });
  if (!res.ok) return null;
  const mimeType = (res.headers.get("content-type") ?? "").split(";")[0].trim();
  if (!mediaKindOf(mimeType)) return null;
  const buffer = Buffer.from(await res.arrayBuffer());
  return scanMedia({ buffer, mimeType, caseId, sourceUrl: url }, synthIdConfig);
}
